

alarm_cooldown_sec: 10

camera_feeds:
  - rtsp://admin:hikVision123@169.254.89.250:554/Streaming/Channels/101
  - rtsp://admin:hikVision123@169.254.89.249:554/Streaming/Channels/101

camera_titles:
  - Ground Floor
  - First Floor

class_file: data/class_names.yaml
confidence_threshold: 0.25
esp_ip: 192.168.45.193
model_path: weights/helmet_model.pt
use_wifi: false
